/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package inf.pucp.edu.pe.vista.simulacion;



import inf.pucp.edu.pe.simulacion.animacion.Core;
import static inf.pucp.edu.pe.simulacion.animacion.Core.Size;
import static inf.pucp.edu.pe.simulacion.animacion.Core.name;
import inf.pucp.edu.pe.vista.principal.PanelImagenVentana;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author JuanCarlos
 */
public class MenuPrincipalSimulacion extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalSimulacion
     */
    
    public static JInternalFrame iframe= new JInternalFrame();
    public MenuPrincipalSimulacion() {
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //this.setLocationRelativeTo(null);
        
        //this.setLocationRelativeTo(null);
        //setBounds(400, 100, 550, 600);
       // PanelImagenVentana p = new PanelImagenVentana();
       // p.setBorder(new EmptyBorder(5, 5, 5, 5));
       // p.setLayout(new BorderLayout(0, 0));
      //  setContentPane(p);
        initComponents();
        
        //inicio la pantalla de simulacion
        
//        this.add(iframe);
//        System.out.println(this.getBounds());
//        iframe.setBounds(0, 62, 800, 600);
//        iframe.setVisible(true);
         Core core= new Core();
      this.add(iframe);
      iframe.add(core);
      iframe.pack();
      
      Size = new Dimension(iframe.getWidth(),iframe.getHeight());
      
      iframe.setTitle(name);
      iframe.setResizable(false);
      //iframe.setLocationRelativeTo(null);
      iframe.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      iframe.setBounds(0, 62, 800, 600);
      iframe.setVisible(true);
      core.start();
        
   
        jToolBar1.setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jButton2 = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuInformacionDeLaSimulacion = new javax.swing.JMenuItem();
        mnuInformacionDeLosSemaforos = new javax.swing.JMenuItem();
        mnuInformacionDeLosVehiculos = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        mnuSimulador = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuAgregarTiempoDeSimulacion = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setRollover(true);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/pucp/edu/pe/Iconos/abriArchivo2.png"))); // NOI18N
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/pucp/edu/pe/Iconos/abriArchivo.png"))); // NOI18N
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton5);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/pucp/edu/pe/Iconos/detener.png"))); // NOI18N
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton6);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/pucp/edu/pe/Iconos/play.png"))); // NOI18N
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton7);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/pucp/edu/pe/Iconos/pausa.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/pucp/edu/pe/Iconos/configuracion.png"))); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Cargar data histórica");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Cargar datos de los vehiculos");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Salir");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Vistas");

        mnuInformacionDeLaSimulacion.setText("Información de la simulación");
        mnuInformacionDeLaSimulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInformacionDeLaSimulacionActionPerformed(evt);
            }
        });
        jMenu2.add(mnuInformacionDeLaSimulacion);

        mnuInformacionDeLosSemaforos.setText("Información de los semaforos");
        mnuInformacionDeLosSemaforos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInformacionDeLosSemaforosActionPerformed(evt);
            }
        });
        jMenu2.add(mnuInformacionDeLosSemaforos);

        mnuInformacionDeLosVehiculos.setText("Información de los vehiculos");
        mnuInformacionDeLosVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInformacionDeLosVehiculosActionPerformed(evt);
            }
        });
        jMenu2.add(mnuInformacionDeLosVehiculos);

        jMenuBar1.add(jMenu2);

        jMenu7.setText("Simulacion");

        jMenuItem7.setText("Ejecutar");
        jMenu7.add(jMenuItem7);

        jMenuItem8.setText("Pausa");
        jMenu7.add(jMenuItem8);

        jMenuItem9.setText("Reiniciar");
        jMenu7.add(jMenuItem9);

        jMenuItem10.setText("Detener");
        jMenu7.add(jMenuItem10);

        mnuSimulador.setText("Simulador");
        mnuSimulador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSimuladorActionPerformed(evt);
            }
        });
        jMenu7.add(mnuSimulador);

        jMenuBar1.add(jMenu7);

        jMenu3.setText("Parametros");

        mnuAgregarTiempoDeSimulacion.setText("Tiempo de simulación");
        mnuAgregarTiempoDeSimulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAgregarTiempoDeSimulacionActionPerformed(evt);
            }
        });
        jMenu3.add(mnuAgregarTiempoDeSimulacion);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ayuda");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 226, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAgregarTiempoDeSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAgregarTiempoDeSimulacionActionPerformed
        // TODO add your handling code here:
        AgregarTiempoDeSimulacion ats= new AgregarTiempoDeSimulacion();
        ats.setVisible(true);
    }//GEN-LAST:event_mnuAgregarTiempoDeSimulacionActionPerformed

    private void mnuInformacionDeLaSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInformacionDeLaSimulacionActionPerformed
        MostrarInformacionDeSimulacion mis= new MostrarInformacionDeSimulacion();
        this.add(mis);
        mis.setVisible(true);
    }//GEN-LAST:event_mnuInformacionDeLaSimulacionActionPerformed

    private void mnuInformacionDeLosSemaforosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInformacionDeLosSemaforosActionPerformed
        MostrarInformacionDeSemaforos mise= new MostrarInformacionDeSemaforos();
        this.add(mise);
        mise.setVisible(true);
        
    }//GEN-LAST:event_mnuInformacionDeLosSemaforosActionPerformed

    private void mnuInformacionDeLosVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInformacionDeLosVehiculosActionPerformed
        MostrarInformacionvehicular miv= new MostrarInformacionvehicular();
        this.add(miv);
        miv.setVisible(true);
    }//GEN-LAST:event_mnuInformacionDeLosVehiculosActionPerformed

    private void mnuSimuladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSimuladorActionPerformed
        // TODO add your handling code here:
        Simulador s= new Simulador();
        this.add(s);
        s.setBounds(0, 62, 1000, 450);
        s.setVisible(true);
    }//GEN-LAST:event_mnuSimuladorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalSimulacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnuAgregarTiempoDeSimulacion;
    private javax.swing.JMenuItem mnuInformacionDeLaSimulacion;
    private javax.swing.JMenuItem mnuInformacionDeLosSemaforos;
    private javax.swing.JMenuItem mnuInformacionDeLosVehiculos;
    private javax.swing.JMenuItem mnuSimulador;
    // End of variables declaration//GEN-END:variables
}
