/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package inf.pucp.edu.pe.vista.simulacion;

import inf.pucp.edu.pe.vista.principal.PanelImagenVentana;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author JuanCarlos
 */
public class Simulador extends javax.swing.JInternalFrame {

    /**
     * Creates new form Simulador
     */
    
    
    public Simulador() {
        this.setBounds(0, 34,1000 , 600);
        //PanelImagenVentana p = new PanelImagenVentana();
       // p.setBorder(new EmptyBorder(5, 5, 5, 5));
        //p.setLayout(new BorderLayout(0, 0));
        //setContentPane(p);
        initComponents();
        this.setBackground(Color.WHITE);
        this.setTitle("Simulador");
        this.setClosable(true);
        this.setMaximizable(false);
        this.setIconifiable(true);     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(1000, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    
    public void paint(Graphics g) 
    { 
        
        super.paint(g); 
        int ancho = 30, alto = 30; 
        for(int i = 1; i <= 100; i++){ 
        g.drawLine(30, i * alto, getSize().width - 100, i * alto); 
        g.drawLine(i * ancho, 30, i * ancho, getSize().height - 100); 
        } 
    }
    
}
